version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    image: domination-backend:latest
    command: uvicorn backend.main_backend:app  --port 3000
    env_file:
      - stack.env
    ports:
      - "3000:3000"


  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: domination-frontend:latest
    command: npm run dev  
    env_file:
      - stack.env
    ports:
      - "5173:5173"


