services:
  domination-auto-update:
    build: .
    container_name: ${CONTAINER_NAME:-domination-auto-update} 
    command: python run.py
    restart: always
    env_file:
      - stack.env
    ports:
      - "${PORT:-8000}:8000"