services:
  app:
    # Imagem oficial do teu repositório no GitHub
    image: ghcr.io/danilofcosta/domination-bot:latest
    container_name: Domination-Bot_telegram
    restart: always
    command: python run.py
    env_file:
      - .env
    ports:
      - "8000:8000"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=20# Verifica atualizações a cada 1 minuto
      - WATCHTOWER_CLEANUP=true     # Apaga a imagem antiga para não encher o disco