version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    image: domination-backend:latest
    command: uvicorn main_back:app --host 0.0.0.0 --port 3000
    env_file:
      - stack.env
    ports:
      - "3000:3000"


  frontend:
    build:
      context: ./web/mywebapp
      dockerfile: dockerfile
    image: domination-frontend:latest
    command: npm run dev -- --host 0.0.0.0
    env_file:
      - stack.env
    ports:
      - "5173:5173"


