version: "3.8"

services:
  backend:
    image: domination-backend:latest
    build:
      context: ./backend
    command: uvicorn main_back:app --host 0.0.0.0 --port 3000
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "3000:3000"
    networks:
      - domination-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: domination-frontend:latest
    build:
      context: ./web/mywebapp
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    networks:
      - domination-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  domination-net:
    driver: overlay
